services:
  app:
    build: .
    container_name: connected-travel-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/var/www/html
      # - ./vendor:/var/www/html/vendor
      # - ./public/build:/var/www/html/public/build
    networks:
      - travel-network
    command: >
      sh -c "composer install && 
             php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --workers=6"

  redis:
    image: redis:alpine
    container_name: connected-travel-redis
    ports:
      - "6379:6379"
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge
